### ISSUE TITLE
[ERROR] Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by bughaver** [DanielHabenicht/MMM-json#5]
```[02.07.2021 10:11.04.874] [ERROR] Error: Cannot find module 'request'

Require stack:

- /opt/magic_mirror/modules/MMM-json/node_helper.js

- /opt/magic_mirror/js/app.js

- /opt/magic_mirror/serveronly/index.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)

    at Function.Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29)

    at Function.Module._load (internal/modules/cjs/loader.js:746:27)

    at Module.require (internal/modules/cjs/loader.js:974:19)

    at require (internal/modules/cjs/helpers.js:92:18)

    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-json/node_helper.js:1:15)

    at Module._compile (internal/modules/cjs/loader.js:1085:14)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

    at Module.load (internal/modules/cjs/loader.js:950:32)

    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [

    '/opt/magic_mirror/modules/MMM-json/node_helper.js',

    '/opt/magic_mirror/js/app.js',

    '/opt/magic_mirror/serveronly/index.js'

  ]

}

**Comment by DanielHabenicht** [comment]
Did you npm install inside of the cloned directory?
What npm/noder version are you using?

**Comment by bughaver** [comment]
Yes I have

npm -v
6.14.4

running 'npm install request' after 'npm install' fixed the issue.

**Comment by Iketaki** [comment]
Hi. I was faced at the same problem. 
Installing `request` manually fixed the issue. Thanks.
